select
    customer_id,
    signed_up_date,
    home_region,
    favored_discipline,
    first_order_date,
    last_order_date,
    order_count,
    billable_order_count,
    completed_order_count,
    shop_count,
    lifetime_order_item_count,
    lifetime_gross_revenue_gold as lifetime_gross_revenue,
    lifetime_discount_gold as lifetime_discount,
    lifetime_net_revenue_gold as lifetime_net_revenue,
    returned_revenue_gold as returned_revenue,
    lifetime_collected_gold as lifetime_collected,
    lifetime_refunded_gold as lifetime_refunded,
    lifetime_net_collected_gold as lifetime_net_collected,
    average_order_value_gold as average_order_value,
    days_to_first_order,
    days_since_last_order,
    has_ordered,
    is_repeat_customer
from {{ ref('int_merlinco_customer_lifetime_rollup') }}
